### ISSUE TITLE
Favicon showing Wordpress Logo in stead of CC Logo

### ISSUE THREAD

**Issue by nasirkhan** [creativecommons/commoners#405] opened 2020-05-18 14:13 UTC
## Describe the bug

https://network.creativecommons.org website showing the Wordpress logo in the favicon icon in stead of CC logo.

## To Reproduce

1. Go to https://network.creativecommons.org
2. Check the browser tab favicon area
3. You will see the Wordpress logo

## Expected behavior
CC logo needed to be used as favicon.

## Screenshots

![Screenshot from 2020-05-18 20-08-49](https://user-images.githubusercontent.com/396987/82222890-bb276080-9943-11ea-9332-ad794d12eae7.png)

## Desktop (please complete the following information)
 - Ubuntu, Firefox

**Comment by kgodey** [comment] 2020-05-18 19:43
This is a duplicate of #399. We're looking into it.

**Closed by kgodey** 2020-05-18 19:43 UTC
Labels: awaiting triage, bug
