### ISSUE TITLE
Homepage width plus boxes size

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#89] opened 2017-11-02 21:56 UTC
Is there a reason why we chose to not using the entire `width` of the homepage on the design? ([see here for the mockup](http://gustavocatalan.com/lab/cc-network/))

Also, on staging the boxes are [vertical](https://share.riseup.net/#h-ImRseDt2t2wwQJXCmAXA) and not [horizontal](https://share.riseup.net/#TgWpxuZXgl0u9sx5-5055A) such on the mockup? I assume is because of the prior.

Also, not a way to include the carrousel?

**Comment by robmyers** [comment] 2017-11-02 22:35
Width is a duplicate of #78 . In addition to BuddyPress profile width needing changing, the Charter looks awful if we make it as wide as the screen.

Width should be 1280px .

The box shape is a product of their relative width, yes.

I will investigate the carousel. We can launch without it but I will try to fix it.

**Comment by claudioruiz** [comment] 2017-11-08 20:36
Is it a way to have different width on different pages? @edmillag

**Comment by edmillag** [comment] 2017-11-08 21:02
its not optimal, and implies extra design work

**Comment by claudioruiz** [comment] 2017-11-08 21:22
@edmillag I'm just trying to help solving the issue. If this requires "extra design work" we should chose an option who doesn't. No idea what it is.

**Comment by edmillag** [comment] 2017-11-08 21:30
@robmyers i understand that the main issue with the 'narrow' style it is because is needed for the pages that uses the buddypress sidebar, right?
What happens with those screens if we put the "wide" style on it? it will looks terrible?
Is there a way to make different styles for those pages inside the admin console, and the public webpages?
please correct me if im wrong

**Comment by robmyers** [comment] 2017-11-09 01:59
@edmillag It's for the BuddyPress profile display, e.g.:

https://commoners-staging.creativecommons.org/members/robcreativecommons-org/

We can target different elements with different CSS selectors, we just need not to be too general (as BuddyPress elements are e.g. a p inside the .item-body as well as a .label) and not too specific (as Gravity Forms field numbers cannot be relied on).

I believe that theme CSS isn't loaded in the Admin, I'm sorry for raising that as an issue, I don't think it's a problem. If it is I'll just hack the theme to make it not be so.

**Comment by edmillag** [comment] 2017-11-09 14:20
actually im not able to see the profile display. im only can see the home page (narrow) on the link you attached. can you add a screenshot @robmyers ?

**Comment by robmyers** [comment] 2017-11-09 18:43
Viewing:

![image](https://user-images.githubusercontent.com/21746/32623136-fa8afb82-c539-11e7-8f88-e100ddbadb2c.png)



Editing:

![image](https://user-images.githubusercontent.com/21746/32623103-e5bc3de2-c539-11e7-9cfb-9401c09c8f2a.png)



Also, applying:

![image](https://user-images.githubusercontent.com/21746/32623353-be7fdc9c-c53a-11e7-8a41-7778cd9908d5.png)

**Comment by robmyers** [comment] 2017-11-09 18:46
Oh ignore the green eyes, that's a developer interface wart for the conditional menus.

**Closed** 2018-01-26 19:37 UTC
